# permissions for end users to view cloudflaredtunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaredtunnel-viewer-role
rules:
- apiGroups:
  - jensrotne.com
  resources:
  - cloudflaredtunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jensrotne.com
  resources:
  - cloudflaredtunnels/status
  verbs:
  - get
