---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jensrotne.com
  resources:
  - cloudflaredtunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jensrotne.com
  resources:
  - cloudflaredtunnels/finalizers
  verbs:
  - update
- apiGroups:
  - jensrotne.com
  resources:
  - cloudflaredtunnels/status
  verbs:
  - get
  - patch
  - update
