apiVersion: jensrotne.com/v1alpha1
kind: CloudflaredTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: jens-tunnel2
  namespace: default
spec:
  targetService: echo-server
  targetPort: 80
