apiVersion: jensrotne.com/v1alpha1
kind: CloudflaredTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: jens-tunnel2
  namespace: default
spec:
  targetService: echo-server
  targetPort: 80
  hostname: 
  ipAddress: '
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/managed-by: kustomize
  name: echo-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - image: hashicorp/http-echo
        name: echo-server
        args:
        - "-text=hello from echo-server"
        ports:
        - containerPort: 5678
        resources: 
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/managed-by: kustomize
  name: echo-server
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5678
  selector:
    app.kubernetes.io/name: echo-server
  type: ClusterIP