apiVersion: jensrotne.com/v1alpha1
kind: CloudflaredTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflared-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaredtunnel-sample
spec:
  # TODO(user): Add fields here
